services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mytestdb
    depends_on:
      - postgres
    networks:
      - myapp-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mytestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp-network

  # Frontend service (Angular)
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - myapp-network
    depends_on:
      - backend

# Define a network to allow services to communicate
networks:
  myapp-network:
    driver: bridge

# Volumes to persist Postgres data
volumes:
  postgres-data:
